Feature/sprites
DariaDostoevskaia/Exercises pull request #1
Opened 2023-08-17 22:16 UTC by DariaDostoevskaia

2023-08-21 19:17 UTC, Overlordshor requested changes

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +            Exercise1(dividend, out int divisor);
name

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +                    || divisor == null)
Условие dividend == null || divisor == null некорректно, так как int - это тип значений (value type) и никогда не может быть равен null. Вы должны проверить ввод пользователя и обработать некорректный ввод.

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +                divisor = Convert.ToInt32(Console.ReadLine());
Ваш метод не считывает значения с консоли. Он просто переписывает аргументы метода, игнорируя ввод пользователя.

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +            Exercise1(dividend, out int divisor);
missing remainder

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +                }
// Ошибка 1: arrayNumber - это int, и он никогда не будет равен null. 
        // Необходимо использовать int.TryParse для проверки корректного ввода пользователя.

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +                }
// Ошибка 2: Если пользователь ввел некорректное значение, вызывается рекурсивный вызов метода, 
        // но значения array и maxValue не меняются, и это может привести к бесконечной рекурсии.

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +                maxValue = array.Max();
// Ошибка 3: array - это массив, но он не проинициализирован, и это может вызвать исключение.

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +                var arrayNumber = Convert.ToInt32(Console.ReadLine());
What for to you an amount of numbers if you already receive a ready array?

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +                }
Why is the user overwriting the array?

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +                   || height == null)
// Ошибка 1: Переменные width и height имеют тип double, 
        // и они не могут быть равны null. Это условие всегда будет ложным.

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +                    CalculateRectangleArea(width, height, out square);
// Ошибка 2: Вы вызываете метод рекурсивно, но передаваемые значения width и height не меняются, 
        // и пользователю снова будет предложено ввести значения, но они не будут использованы в расчетах.

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +                height = Convert.ToDouble(Console.ReadLine());
// Ошибка 3: Вычисления производятся после того, как значения width и height были перезаписаны значениями 
    // из консоли, поэтому расчет будет произведен на основе новых, введенных пользователем значений, 
    // а не переданных аргументов метода.

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +                   || secondNumber == null)
// Ошибка 1: Параметры firstNumber и secondNumber имеют тип int, и они не могут быть равны null. 
        // Это условие всегда будет ложным.

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +                    Swap(firstNumber, secondNumber, out swapNumbers);
// Ошибка 2: Вы вызываете метод рекурсивно, но передаваемые значения firstNumber и secondNumber не меняются, 
        // и пользователю снова будет предложено ввести значения, но они не будут использованы в обмене.

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +                swapNumbers = new int[] { firstNumber, secondNumber };
// Ошибка 3: Обмен чисел не происходит. Вместо этого, просто выводится массив, содержащий два введенных числа.

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +                if (inputString == null)
if the string will be equal to "" or " "

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +                    TryParseInt(inputString, out result);
// Ошибка 2: Вы вызываете метод рекурсивно, но передаваемое значение inputString не меняется, 
        // и пользователю снова будет предложено ввести значение, но оно не будет использовано для парсинга.

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +            void TryParseInt(string inputString, out bool result)
Используйте ключевое слово out, чтобы вернуть результат преобразования в виде целого числа.

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +            void TryParseInt(string inputString, out bool result)
Если преобразование успешно, метод должен вернуть true, иначе - false.
The return should be instead of the void

2023-08-21 19:17 UTC, Overlordshor commented on Program.cs
> +                inputString = Convert.ToString(Console.ReadLine());
Why is the string overwritten?

2023-08-27 13:31 UTC, Overlordshor requested changes
omitted comments

2023-09-03 12:16 UTC, Overlordshor commented on Program.cs
> +            CalculateDivision(dividend, out int divisor);
Создайте метод Divide, который принимает два целочисленных аргумента: dividend и divisor
 Метод должен вычислить частное и остаток от деления

2023-09-03 12:16 UTC, Overlordshor commented on Program.cs
> +                divisor /= dividend;
Метод должен вычислить частное и остаток от деления

2023-09-03 12:16 UTC, Overlordshor commented on Program.cs
> +            Exercise1(dividend, out int divisor);
@DariaDostoevskaia

2023-09-03 12:18 UTC, Overlordshor requested changes

2023-09-03 12:18 UTC, Overlordshor commented on Program.cs
> +            void TryParseInt(string inputString, out int result)
Если преобразование успешно, метод должен вернуть true, иначе - false

2023-09-13 18:06 UTC, Overlordshor commented on Program.cs
> +            Console.WriteLine(resultBool);
The method should return a Boolean value, but the parsing result is expected to be out

2023-09-13 18:06 UTC, Overlordshor commented on Program.cs
> +            void TryParseInt(string inputString, out int result)
-

2023-09-15 16:32 UTC, Overlordshor requested changes
https://discord.com/channels/1130132845608828939/1130136875152191528/1152280045860180048

2023-09-23 13:36 UTC, DariaDostoevskaia commented
https://tracker.yandex.ru/SPRINT-7

2023-09-24 19:37 UTC, Overlordshor approved these changes

2023-09-25 20:07 UTC, closed without merging