Feature/object oriented programming
DariaDostoevskaia/Exercises pull request #3
Opened 2023-09-13 15:43 UTC by DariaDostoevskaia

2023-09-13 18:08 UTC, Overlordshor requested changes
The solution didn't hit.
You need to highlight the branch in the place where the solutions were added

2023-09-13 18:08 UTC, Overlordshor commented on obj/Debug/net7.0/Exercises.assets.cache
Remove obj and bin folders from git

2023-09-15 17:12 UTC, Overlordshor requested changes
Пока еще это не ООП :)
Попробуй посмотреть доп видео, сейчас скину подборку авторитетных блоггеров)
https://www.youtube.com/watch?v=fel7jg_YN34
https://www.youtube.com/watch?v=6hgCbOUp-Rs&list=PLuGqgO5WmeGPTZqDHZDIum3h7HnfBfzmZ&index=13
https://www.youtube.com/watch?v=bkGKQ3pY6kE

https://www.youtube.com/watch?v=rZcTaRU7AAw&list=PLQOaTSbfxUtBm7DxblJZShqBQnBAVzlXX&index=1&t=610s

2023-09-15 17:12 UTC, Overlordshor commented on Program.cs
> +        }
each class must be in its own file

2023-09-15 17:12 UTC, Overlordshor commented on Program.cs
> +            var person = new Person();
1. Ваш класс Person содержит поля _personSurname, _personName, _personAge, которые вы используете для хранения имени, фамилии и возраста. Обратите внимание, что в C# рекомендуется использовать приватные поля (private) вместо публичных полей. В данном случае, поля должны быть private.

2. Вы используете методы GetSurname, GetName, GetAge для установки значений фамилии, имени и возраста. Однако, обычно в C# для установки значений полей используются свойства (properties). Это обеспечивает лучшую инкапсуляцию данных и контроль над доступом к полям.

3. Метод WritePersonData позволяет устанавливать все три значения сразу, но в классе Person вы также имеете открытые свойства, которые могут быть установлены напрямую. Это может привести к несогласованным данным, если значения устанавливаются разными методами.

2023-09-15 17:12 UTC, Overlordshor commented on Program.cs
> +            public void GetSurname(string personSurname)
The method must internally execute what it is named.
The get method cannot change object data, this is unexpected behavior

2023-09-15 17:12 UTC, Overlordshor commented on Program.cs
> +                $" is a {nameof(Teacher)}, {teacher.PersonAge} years old");
1. Вы создали классы Student и Teacher, которые наследуются от класса Person. Это хороший способ использования наследования в ООП для обобщения общих характеристик между студентами, учителями и персонами в целом.

2. Оба класса Student и Teacher наследуют от класса Person все его поля и свойства. Это позволяет использовать уже определенные в классе Person характеристики, такие как имя, фамилия и возраст, без необходимости их повторного определения в классах Student и Teacher.

3. Однако, ваши классы Student и Teacher пока не добавляют ничего нового кроме того, что уже есть в классе Person. Вы можете добавить дополнительные поля и методы, характерные именно для студентов и учителей, чтобы сделать их классы более функциональными.

2023-09-15 17:12 UTC, Overlordshor commented on Program.cs
> +            //Exercise 2;
Добавьте дополнительные поля и методы, характерные для студентов и учителей, такие как оценки для студентов и предметы для учителей.

2023-09-15 17:12 UTC, Overlordshor commented on Program.cs
> +            surName = "Datchin";
What are you trying to do here?

2023-09-15 17:12 UTC, Overlordshor commented on Program.cs
> +            person1.GetSurname(surName);
Get is not set

2023-09-15 17:12 UTC, Overlordshor commented on Program.cs
> +                _personAge = age;
Shouldn't overwrite the object's value

2023-09-15 17:12 UTC, Overlordshor commented on Program.cs
> +                _personAge = age;
You call the object's print method to print it.

2023-09-15 17:12 UTC, Overlordshor commented on Program.cs
> +                                       myPerson.PersonAge);
I think you thought it looked bad too

Just fix the method annotation in the class so that it looks like a regular public method.

2023-09-15 17:12 UTC, Overlordshor commented on Program.cs
> +            private List<Teacher> _teachers = new();
We don't need to store teachers and students in different lists, because... they all implement the same interface, so you can use the interface type or the parent class

2023-09-15 17:12 UTC, Overlordshor commented on Program.cs
> +            public List<Teacher> Teachers => _teachers;
You and I implemented these methods in the project via OfType<>

2023-09-15 17:12 UTC, Overlordshor commented on Program.cs
> +                _students.Add(student);
Can be unified by adding a person

2023-09-15 17:12 UTC, Overlordshor commented on Program.cs
> +                _students.RemoveAt(0);
Why are we deleting only the first one?

2023-09-15 17:12 UTC, Overlordshor commented on Program.cs
> +        public class Classroom
IPrintable
It can also implement the data interface.
This is different from inheritance by classes.
We inherit classes based on general structural data and methods.

And the interfaces follow the general logic of work.

Those. any class in theory can be IPrintable

2023-09-23 08:34 UTC, DariaDostoevskaia commented on Program.cs
> +        }
+?

2023-09-23 12:39 UTC, DariaDostoevskaia commented on obj/Debug/net7.0/Exercises.assets.cache
+?

2023-09-23 12:59 UTC, DariaDostoevskaia commented on Program.cs
> +        public class Classroom
+?

2023-09-23 13:00 UTC, DariaDostoevskaia commented
https://tracker.yandex.ru/AI-3

2023-09-24 19:47 UTC, Overlordshor requested changes

2023-09-24 19:47 UTC, Overlordshor commented on Program.cs
> +            var student = new Student();
When we say we work in OOP, we must create a model that is already completely valid.
To do this, through the constructor we pass the parameters that are necessary for the model. Without them, the model makes no sense.

For example, a student can be without estates, without age?
If not, then create these arguments in the constructor.

2023-09-24 19:47 UTC, Overlordshor commented on Program.cs
> +        }
Such a record is possible, but it makes no sense to return it to a getter via a method.

It is also much less readable on its own.
Use auto properties or methods.

2023-09-24 19:47 UTC, Overlordshor commented on Program.cs
> +        }
Need to split into separate files

2023-09-24 19:47 UTC, Overlordshor commented on Program.cs
> +            _persons.Add(_student);
All links will be added here, because... there is nowhere for people to come from

2023-09-24 19:47 UTC, Overlordshor commented on Program.cs
> +            }
Haven't you checked?
There will be a collection change exception.
There is another method that will work

2023-09-24 19:47 UTC, Overlordshor commented on Program.cs
> +        }
It's much better than RemovePersons()

2023-09-24 19:47 UTC, Overlordshor commented on Program.cs
> +        }
Should display information about all persons in the class

2023-09-24 19:47 UTC, Overlordshor commented on Program.cs
> +        private Teacher _teacher;
Why are these separate fields?

2023-09-26 13:26 UTC, DariaDostoevskaia commented on Program.cs
> +        }
+

2023-09-27 17:50 UTC, DariaDostoevskaia commented on Program.cs
> +        private Teacher _teacher;
+

2023-09-29 14:45 UTC, closed without merging